version: '3'
services:
  # Frontend Container
  frontend:
    build: ./frontend
    ports:
      - '80:80'
      - '443:443'
    container_name: intelliq-frontend
    restart: always
    depends_on:
      api-backend:
        condition: service_healthy
  # API Backend Container
  api-backend:
    build: ./api-backend
    ports:
      - '9103:9103'
    container_name: intelliq-api
    restart: always
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: "curl --insecure -f https://localhost:9103/intelliq_api/admin/healthcheck"
      interval: 1s
      timeout: 5s
      retries: 3
      start_period: 1s
  # Database Container
  database:
    image: mariadb
    ports:
      - '3306:3306'
    container_name: intelliq-database
    restart: always
    volumes:
      - './scripts/mariadb/schema.sql:/docker-entrypoint-initdb.d/init.sql'
      - './data/mariadb:/var/lib/mysql'
    environment:
      MARIADB_USER: intelliq
      MARIADB_PASSWORD: intelliq
      MARIADB_DATABASE: intelliq
      MARIADB_ROOT_HOST: localhost
      MARIADB_RANDOM_ROOT_PASSWORD: yes
    healthcheck:
      test: "mysql --user=intelliq --password=intelliq --execute \"SHOW DATABASES;\""
      interval: 1s
      timeout: 5s
      retries: 3
      start_period: 1s